language: python
python:
    - "3.5"
install:
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - hash -r 
    - conda config --set always_yes yes --set changesps1 no
    - conda update -q conda
    - conda env create -f conda_environment.yml
    - conda activate diss
    - pip install ./libraries

script:
    - for filename in $(ls tests/isaac_tests/*.py); do; coverage run -a --source=libraries/isaac $filename; done
    - coverage report -m

branches:
    only:
        - master
