language: python
python:
    - "3.5"

addons:
  apt_packages:
    - libhdf5-serial-dev

install:
    # - sudo apt-get install -y libhdf5-dev
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r 
    - conda config --set always_yes yes --set changeps1 no

    - conda env create -f conda_environment.yml
    - conda activate diss
    - pip install ./libraries

script:
    - for filename in $(ls tests/isaac_tests/*.py); do coverage run -a --source=libraries/isaac $filename; done
    - coverage report -m

sudo: required

branches:
    only:
        - master
