name: diss
channels:
    - kne
    - r
    - defaults
    - conda-forge
    - pytorch
dependencies:
    - python=3.5
    - pandas
    - rpy2
    - pytorch=1.0.1
    - torchvision
    - cudatoolkit=9.0
    - h5py
    # - python-blosc
    - python-lzo
    - pip
    - pip:
        - cython
        - notebook==5.6.0
        - tzlocal
        - scikit-learn
        - tables
        - gizeh==0.1.11
        - pygame
    - pybox2d
    - matplotlib
    - seaborn
    - scipy
    - moviepy
    - imageio=2.4.1
    - requests
    - jupyter_contrib_nbextensions
    - coverage
