name: diss
channels:
    - kne
    - r
    - defaults
    - conda-forge
    - pytorch
dependencies:
    - python=3.5
    - pandas
    - rpy2
    - pytorch=1.0.1
    - torchvision
    - cudatoolkit=9.0
    - pip
    - pip:
        - notebook==5.7.8
        - tzlocal
        - scikit-learn
        - tables
        - gizeh==0.1.11
    - pybox2d
    - matplotlib
    - seaborn
    - scipy
    - moviepy
    - imageio=2.4.1
    - requests
